# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a602cbbab6997287f4a28f3091cb84cc615717d701c85c8890761a107f6a67057c8299b712db74d3036cc52a551f51619bd5a26808d77239c4f09efe091461e4

test:
  secret_key_base: 68aa474c91b6213a44bd807e8cb5d66f6876d14b51f1bea0e4cb5abe3723bf203718f4e1ed1bf1845b0e3fdc676b82432ac58ab0c6c924e10a8403c2b073951b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
