Site.create(
  name:"St. Luke's Episcopal ESL",
  address:"426 East Fourth Plain Blvd.",
  city:"Vancouver",
  state:"WA",
  country:"USA",
  zip:"98663",
  description:"There are FREE ESL classes offered for all levels of English each Tuesday, Wednesday, and Thursday, 9:30am April 12-June 15th, 2016. (Wednesdays are conversation circle format, Tuesday and Thursdays are more structured)",
  contact:"Jeanne Stephens",
  phone:"360-696-0181",
  email:"jmorsestephens@gmail.com",
  url:"",
  class_resource:"Class",
  site_type: "Church",
  happening_now:"No",
  notes:"Classes have been cancelled due to lack of resources, especially childcare and consistent volunteer tutors. - Stephanie 6/22/16",
  region: "Clark County",
  summer_classes: "No",
  students_served:
)
Site.create(
  name:"Kaplan International College",
  address:"600 SW 10th Ave.",
  city:"Portland",
  state:"OR",
  country:"USA",
  zip:"97205",
  description:"Tuition Based Program",
  contact:"",
  phone:"",
  email:"",
  url:"http://www.kaplaninternational.com/schools/usa/english-courses-portland-usa.aspx",
  class_resource: "Class",
  site_type: "For-Profit Business",
  happening_now:"Yes",
  notes:"",
  region: "Downtown",
  summer_classes: "Yes",
  students_served:
)
Site.create(
  name:"Rockwood Library- Multnomah County Library",
  address:"17917 SE Stark St.",
  city:"Gresham",
  state:"OR",
  country:"USA",
  zip:"",
  description:"No registration required, Multi-level ESL class. Mon-Tues: 6-7:30pm Tue-Thu: 12-1:30pm",
  contact:"Reid Craig",
  phone:"503-988-5396",
  email:"reidc@multcolib.org",
  url:"https://multcolib.org/library-location/rockwood",
  class_resource:"Class",
  site_type: "Library",
  happening_now:"Yes",
  notes:"",
  region: "Gresham",
  summer_classes:"",
  students_served:
)
Site.create(
  name:"SOAR- Citizenship Classes",
  address:"502 State Street",
  city:"Hood River",
  state:"OR",
  country:"USA",
  zip:"97031",
  description:"Free. Sundays. January 3-March 6. 5:30 p.m. – 8:00 p.m. Classes are designed to prepare students for the U.S. Naturalization Test, which includes an evaluation of speaking, reading, and writing abilities in English, as well as questions about U.S. history and government.",
  contact:"",
  phone:"503.384.2482",
  email:"",
  url:"facebook.com/SOARLegal",
  class_resource:"Class",
  site_type: "Social Service/Government/Non-Profit",
  happening_now:"Yes",
  notes:"Contact Jaymee Martin",
  region: "Other Areas",
  summer_classes:"",
  students_served:
)
Site.create(
  name:"Cesar Chavez Elementary",
  address:"5103 N. Willis Blvd.",
  city:"Portland",
  state:"OR",
  country:"USA",
  zip:"97203",
  description:"Free, Open-Entry Spanish and English Classes for Adults. Check in at the front office. Classes are held every Tuesday and Friday from 8-9:30am.",
  contact:"Will Reese",
  phone:"503-916-5904",
  email:"",
  url:"",
  class_resource:"Class",
  site_type: "Public School",
  happening_now:"Yes",
  notes:"",
  region: "North/Northeast",
  summer_classes:"",
  students_served:
)
Site.create(
  name:,
  address:,
  city:,
  state:,
  country:,
  zip:,
  description:,
  contact:,
  phone:,
  email:,
  url:,
  class_resource: "Resource",
  site_type: "",
  happening_now:,
  notes:,
  region: "South/Southeast",
  summer_classes:,
  students_served:
)
Site.create(
  name:,
  address:,
  city:,
  state:,
  country:,
  zip:,
  description:,
  contact:,
  phone:,
  email:,
  url:,
  class_resource:,
  site_type: "Community College of University",
  happening_now:,
  notes:,
  region: "Southwest",
  summer_classes:,
  students_served:
)
Site.create(
  name:,
  address:,
  city:,
  state:,
  country:,
  zip:,
  description:,
  contact:,
  phone:,
  email:,
  url:,
  class_resource:,
  site_type: "Social Service/Government/Non-Profit",
  happening_now:,
  notes:,
  region: "Washington County",
  summer_classes:,
  students_served:
)
